#!/usr/bin/env python3
"""Static audit of luci-theme-footstrap CSS/JS.

The CSS source is the styles/ tree (one directory per cascade layer); cascade.css
is generated by build-css.sh and is not read here (see docs/17).

Reports:
  1. Bracket balance for every CSS source file and all *.js.
  2. CSS custom properties used via var() but never defined (broken refs) —
     these silently drop the declaration (missing shadows/colors).
  3. Hardcoded color literals in styles/base/*.css that bypass the token bridge —
     un-themed spots a palette switch cannot reach.
  4. !important outside the files allowed to carry it. Every remaining flag
     fights an inline style= attribute or carries a widget's internal layout; a
     new one anywhere else means a rule belongs in a later cascade layer.
  5. Declarations shadowed inside a layer: the same selector, in the same layer
     and the same at-rule context, setting the same property twice. The earlier
     one is dead. Reported only for `theme` and `page`, where it always means a
     rule was appended instead of edited; `base` re-states properties on purpose
     (the reset sets `input { font-size: 100% }`, forms then sets 13px).

No dependencies. Run from repo root:
  .claude/tooling/preview-venv/bin/python .claude/skills/footstrap-audit/audit.py
  (any python3 works; venv just guarantees one exists)

For behavioural checks (did a change alter any computed style?) use cssdiff.py
in this same directory — a static audit cannot see the cascade.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3] / "luci-theme-footstrap"
STYLES = ROOT / "styles"
BASE = STYLES / "base"
# the only files allowed an !important. In 90-responsive/20-overview the flags
# outrank an inline style= attribute written by luci-mod-status (29_ports.js) or
# ui.js, which no cascade layer can do. In styles/base they carry widget-internal
# layout (.cbi-dropdown) or a forcing utility (.left/.right/.center).
BANG_OK = {"90-responsive.css", "20-overview.css"} | {p.name for p in (STYLES / "base").glob("*.css")}

# vars set at runtime (inline style / other files) — legitimately "undefined" here
VAR_ALLOW = {"--zone-color-rgb", "--focus-color-rgb", "--on-color"}

def balance(path):
    s = path.read_text(encoding="utf-8")
    bad = [f"{a}{b} {s.count(a)}/{s.count(b)}"
           for a, b in [("{", "}"), ("(", ")"), ("[", "]")] if s.count(a) != s.count(b)]
    return bad

def audit_vars(s):
    defined = set(re.findall(r"(--[a-zA-Z0-9-]+)\s*:", s))
    used = set(re.findall(r"var\((--[a-zA-Z0-9-]+)", s))
    return sorted(u for u in (used - defined) if u not in VAR_ALLOW)

def base_hardcoded(lines):
    sel, out = "", []
    for i, l in enumerate(lines):
        st = l.strip()
        if st.endswith("{"):
            sel = st[:-1].strip()
        if not st.startswith("--") and "--" not in l.split(":")[0]:
            # a real literal = #hex, or a colour function whose first arg is a
            # number (not var()); black/white alpha overlays are ignored.
            after_var = re.sub(r"var\([^()]*\)", "", l)
            lit = re.search(r"#[0-9a-fA-F]{3,8}\b", after_var)
            func = re.search(r"[rh]sla?\(\s*(\d[\d.]*)", after_var)
            if func and re.match(r"(0\s*,\s*0\s*,\s*0|255\s*,\s*255\s*,\s*255)",
                                 after_var[func.start():].split("(", 1)[1].lstrip()):
                func = None
            if lit or func:
                out.append((i + 1, sel[:46], st[:80]))
    return out

# --- rule parsing (enough CSS to spot duplicate selectors; no nesting beyond
# --- @layer / @media / @supports / @container, which is all this tree uses)
def _strip_comments(src):
    out, i = [], 0
    while i < len(src):
        j = src.find("/*", i)
        if j < 0:
            out.append(src[i:]); break
        out.append(src[i:j])
        k = src.find("*/", j + 2)
        if k < 0: break
        i = k + 2
    return "".join(out)

def _split_selectors(head):
    """split on top-level commas only — :is()/:not() may contain their own"""
    out, depth, cur = [], 0, ""
    for ch in head:
        if ch == "(": depth += 1
        elif ch == ")": depth -= 1
        if ch == "," and depth == 0:
            if cur.strip(): out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip(): out.append(cur.strip())
    return out

def rules(path):
    """yield (line, layer, context, selector, [(prop, value)…]) for one file"""
    src = path.read_text(encoding="utf-8")
    s = _strip_comments(src)
    stack, buf, i = [], "", 0
    while i < len(s):
        c = s[i]
        if c == "{":
            head, buf = buf.strip(), ""
            if head.startswith("@"):
                stack.append(head); i += 1; continue
            depth, j = 1, i + 1
            while j < len(s) and depth:
                depth += (s[j] == "{") - (s[j] == "}")
                j += 1
            body, line = s[i + 1:j - 1], s.count("\n", 0, i) + 1
            layer = next((h.split()[1] for h in stack if h.startswith("@layer ")), "")
            ctx = " ".join(h for h in stack if not h.startswith("@layer"))
            if not re.fullmatch(r"[\d.%,\s]+|from|to", head):   # skip @keyframes stops
                decls = []
                for d in body.split(";"):
                    d = d.strip()
                    if d and ":" in d and not d.startswith("--"):
                        prop, val = d.split(":", 1)
                        decls.append((prop.strip(), val.strip()))
                sels = _split_selectors(head)
                for sel in sels:
                    yield line, layer, ctx, sel, decls, len(sels)
            i = j; continue
        if c == "}":
            if stack: stack.pop()
            buf = ""; i += 1; continue
        buf += c; i += 1

def audit_shadowed(css):
    """Same selector + layer + at-rule context, same property set twice: the
    earlier declaration is dead.

    Skipped when the earlier rule carried MORE selectors than the later one.
    That is the group-then-refine idiom — `input…, textarea { min-height: 38px }`
    followed by `textarea { min-height: 84px }` — where the first declaration is
    still doing work for the other members of the group. What we are hunting is
    the opposite: a rule appended at the bottom of the file restating a selector
    already styled above, which is how a stylesheet turns into a changelog."""
    seen, out = {}, []
    for p in css:
        for line, layer, ctx, sel, decls, nsel in rules(p):
            if layer not in ("theme", "page"):
                continue
            for prop, val in decls:
                k = (layer, ctx, sel, prop)
                if k in seen:
                    pf, pl, pv, pn = seen[k]
                    if pn <= nsel:
                        out.append((sel, prop, pf, pl, pv, p.name, line, val))
                seen[k] = (p.name, line, val, nsel)
    return out

def sources():
    """Every source file, in the order build-css.sh concatenates them."""
    return (sorted(STYLES.glob("*.css"))
            + sorted((STYLES / "base").glob("*.css"))
            + sorted((STYLES / "theme").glob("*.css"))
            + sorted((STYLES / "pages").glob("*.css")))

def main():
    if not BASE.is_dir():
        sys.exit(f"not found: {BASE}")
    css = sources()
    s = "\n".join(p.read_text(encoding="utf-8") for p in css)

    print("== balance ==")
    problems = []
    for p in [*css, *sorted(ROOT.glob("htdocs/luci-static/resources/**/*.js"))]:
        b = balance(p)
        if b:
            problems.append(p)
            print(f"  BAD {p.relative_to(ROOT)}: {', '.join(b)}")
    if not problems:
        print("  ok (all balanced)")

    print("\n== css vars used but not defined ==")
    miss = audit_vars(s)
    print("  none" if not miss else "\n".join(f"  {m}  (x{s.count('var('+m)})" for m in miss))

    print("\n== !important outside the files allowed to carry it ==")
    stray = []
    for p in css:
        if p.name in BANG_OK:
            continue
        for i, l in enumerate(p.read_text(encoding="utf-8").split("\n"), 1):
            # a flag that terminates a declaration; prose in a comment does not
            if re.search(r"!important\s*[;}]", l):
                stray.append((p.name, i, l.strip()[:70]))
    if not stray:
        print("  none")
    else:
        for name, ln, txt in stray:
            print(f"  {name}:{ln}  {txt}")
        print("  -> move the rule to a later layer, or merge it with its twin")

    print("\n== declarations shadowed within a layer (theme/page) ==")
    sh = audit_shadowed(css)
    if not sh:
        print("  none")
    else:
        for sel, prop, pf, pl, pv, f, ln, v in sh:
            same = "  SAME VALUE" if pv == v else ""
            print(f"  {sel} {{ {prop} }}  {pf}:{pl} {pv!r} -> {f}:{ln} {v!r}{same}")
        print(f"  ({len(sh)} dead) -> edit the first rule instead of appending a second")
        print("     (group-then-refine, e.g. a shared input rule narrowed for textarea, is not reported)")

    print("\n== hardcoded colors in styles/base (candidates to tokenize) ==")
    hc = [(p.name, ln, sel, txt)
          for p in sorted(BASE.glob("*.css"))
          for ln, sel, txt in base_hardcoded(p.read_text(encoding="utf-8").split("\n"))]
    if not hc:
        print("  none")
    else:
        for name, ln, sel, txt in hc:
            print(f"  {name}:{ln:<4} [{sel}] {txt}")
        print(f"  ({len(hc)} lines)")

    print("\nTip: compile-check ucode templates on the router:")
    print("  ssh router 'for f in /usr/share/ucode/luci/template/themes/footstrap*/*.ut; do "
          "ucode -T -c -o /dev/null \"$f\" && echo OK $f || echo FAIL $f; done'")

if __name__ == "__main__":
    main()
